# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MDhiMmQ4NzUzYmQ2ZDA0OWFkZjQ3MTBjYjA2N2FmNTc0NGNjNzBlODhmMGIzODQxZDgxZDk1OWZmYWFiYmFjYzc2N2MwZTI2NzdiMzRkZjY2N2Y5YTI4OTY0NDk3MzhiNTUyNzdhZDNiOTMyYzMzMzM0ZDY5YzcwYTA5YmQ1ZTY=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: jhipsterSampleApplication
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: jhipsterSampleApplication
    password:
